/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from "../..";
import address from "./address";
import name_ from "./name";
import phone_number from "./phone_number";
import commerce from "./commerce";
import date from "./date";
import hacker from "./hacker";

const zh_CN: LocaleDefinition = {
  title: "Chinese",
  address,
  name: name_,
  phone_number,
  commerce,
  date,
  hacker,
};

export default zh_CN;
