/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from "../..";
import address from "./address";
import name_ from "./name";
import phone_number from "./phone_number";
import commerce from "./commerce";
import date from "./date";
import hacker from "./hacker";
import word from "./word";

const zh_CN: LocaleDefinition = {
  title: "Chinese",
  address,
  name: name_,
  phone_number,
  commerce,
  date,
  word,
};

export default zh_CN;
