/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { NameDefinitions } from "../../..";
import first_name from "./first_name";
import last_name from "./last_name";
import name_ from "./name";

const name: NameDefinitions = {
  female_first_name: last_name,
  first_name: last_name,
  last_name: first_name,
  male_first_name: last_name,
  binary_gender: [],
  female_middle_name: [],
  male_middle_name: [],
  middle_name: [],
  gender: [],
  prefix: [],
  suffix: [],
  name: [],
};

export default name;
