/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from "../..";
import address from "./address";
import cell_phone from "./cell_phone";
import lorem from "./lorem";
import name_ from "./name";
import phone_number from "./phone_number";
import word from "./word";
import commerce from "./commerce";
import date from "./date";

const ja: LocaleDefinition = {
  title: "Japanese",
  address,
  cell_phone,
  lorem,
  name: name_,
  phone_number,
  word,
  commerce,
  date,
};

export default ja;
